name: Deploy

on: 
  workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        uses: agentifyme/agentifyme-gha@main
        with:
          environment: 'production'
